version: "3.7"

services:
    api:
        container_name: kards_api
        build: api
        restart: always
        command: python manage.py runserver 0.0.0.0:8080
        networks:
            - api-network
        ports:
            - 5050:8080

    app:
        container_name: kards_app
        build: app
        restart: always

    web:
        container_name: kards_web
        build: web
        restart: always
        command: python manage.py runserver 0.0.0.0:8080
        networks:
            - api-network
        ports:
            - 8050:8080

networks:
    api-network: