version: "3.7"

services:
    api:
        container_name: api
        build: api
        restart: always
        networks:
            - api-network
        ports:
            - 5000:80

    app:
        container_name: app
        build: app
        restart: always

    web:
        container_name: web
        build: web
        restart: always
        networks:
            - api-network
        ports:
            - 8000:80

    venv:
        container_name: venv
        build: venv
        restart: always

networks:
    api-network: